import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Space_Grotesk } from "next/font/google";
import "./styles/globals.css";
import { DragDropManager } from "@dnd-kit/react";

const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jakartaSans.variable} ${spaceGrotesk.variable} antialiased`}
      >
        <header className="flex flex-row justify-center bg-fuchsia-200 text-4xl text-black ">
          <div className=" text-4xl text-black">Header</div>
        </header>
        <DragDropManager>

        {children}
        </DragDropManager>
        <footer className="flex flex-row justify-center bg-fuchsia-200 text-4xl text-black ">
          <div className=" text-4xl text-black">footer</div>
        </footer>
      </body>
    </html>
  );
}
